#!/usr/bin/with-contenv bash
set -e

mkdir -p \
    /var/lib/transmission \
    /var/lib/transmission/config \
    /var/lib/transmission/downloads \
    /var/lib/transmission/incomplete \
    /var/lib/transmission/torrents \
    ;

# ensure conf json exists
if [ -r /var/lib/transmission/config/settings.json ];
then
    echo "Found pre-existing Transmission settings.";
else
    echo "Copying default Transmission settings.";
    cp /defaults/settings.json /var/lib/transmission/config/settings.json;
    cp /defaults/stats.json /var/lib/transmission/config/stats.json;
fi;

# NEVER run -R on dl locations
chown -R ${S6_USER:-alpine}:${PGID:-1000} \
    /var/lib/transmission/config \
    ;

chown ${S6_USER:-alpine}:${PGID:-1000} \
    /var/lib/transmission \
    /var/lib/transmission/downloads \
    /var/lib/transmission/incomplete \
    /var/lib/transmission/torrents \
    ;
